### ISSUE TITLE
このリポジトリはアーカイブにした方が良いのではないか

### ISSUE THREAD

**Issue by dynamis** [wot-jp-community/wot-deployment#16]
[w3c/wot-jp-cg](https://github.com/w3c/wot-jp-cg/) にマージ・移動されたのでこちらのリポジトリは今後 w3c/wot-jp-cg で継続編集すると明記した上でアーカイブ設定した方が良いかと思いますが如何でしょうか。

https://docs.github.com/ja/github/creating-cloning-and-archiving-repositories/archiving-repositories

**Comment by dynamis** [comment]
アーカイブにしてしまう前にリダイレクト設定 #17 はしておきたい。

**Comment by k-toumura** [comment]
今年度のdeployment TF活動が正式に始まった時点で:

- 何らかの公開資料を置く場所として使うのであればこのまま利用
- 公開資料はw3c/wot-jp-cg側に置くようにしてこのレポジトリはarchive設定

のどちらかにするかを決めるというのはどうでしょうか?

また、archive設定にかかわりなく、docs以下のコンテンツはw3c/wot-jp-cgで継続編集する、とは書いておいたほうがよさそうです。

**Comment by dynamis** [comment]
クローズしてアーカイブします。
Netlify のリダイレクト用デプロイも一応更新可能な状態に維持。
