### ISSUE TITLE
wot-deployment.netlify.app から wot-jp-cg.netlify.app へとリダイレクトする

### ISSUE THREAD

**Issue by dynamis** [wot-jp-community/wot-deployment#17]
https://wot-jp-cg.netlify.app/ を CG の正式サイトとして[アナウンスされた](https://www.w3.org/community/wot-jp/2021/05/06/wot-jp-cg-webpage/) ことだし、このリポジトリをデプロイしているサイトはリダイレクトしましょうか？

https://wot-deployment.netlify.app/  -> https://wot-jp-cg.netlify.app/ 

してしまって良ければ _redirect ファイルを追加します。

**Comment by k-toumura** [comment]
はい。リダイレクトしてしまったほうが混乱がなく良いと思います。
設定よろしくお願いいたします。
